[tasks."pre-commit:typos"]
run = "typos"

[tasks.pre-commit]
depends = ["pre-commit:*"]

[tasks."pre-commit:cargo-fmt"]
run = "cargo fmt --check"

[tasks.test]
run = "cargo test --no-fail-fast -- ${usage_filters}"
usage = 'arg "[filters]" var=#true'
