[package]
name = "future-warden-mailbox"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"

[dependencies]
tokio = { version = "1.48.0", features = ["sync"], optional = true }

[dev-dependencies]
tokio = { version = "1.48.0", features = ["sync", "rt", "macros"] }
