[package]
name = "future-warden-message-queue"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", features = ["sync"], optional = true }

[dev-dependencies]
tokio = { version = "1.48.0", features = ["sync", "rt", "macros"] }
